---
## thesis metadata
title: |
            A Leeds University Thesis \
            Template for R Markdown
author:                 Your Name
department:             Your School or Faculty
university:             University of Leeds
university-logo:        crest.pdf
thesis-requirements:    Submitted in accordance with the requirements for the degree of
thesis-degree:          Doctor of Philosophy
thesis-date:            February 2021

## frontmatter files
abstract: |
  `r paste(readLines("content/00-frontmatter/_abstract.Rmd"), collapse = '\n  ')`
acknowledgements: |
  `r paste(readLines("content/00-frontmatter/_acknowledgements.Rmd"), collapse = '\n  ')`
dedication: |
  `r paste(readLines("content/00-frontmatter/_dedication.Rmd"), collapse = '\n  ')`
abbreviations: "content/00-frontmatter/abbreviations" # path to .tex file with abbreviations

## bibliography
bib-files: content/references.bib
# bib-pdf-heading: References           # default: References
csl: theme/web/ieee.csl

## correction highlighting
# corrections-pdf-disabled: true        # true or commented out
# corrections-col: CCCCFF               # any HTML colour

## document setup
# document-for-print: true              # true or commented out
document-dark-mode: false
# document-pdf-bind: true               # true or commented out

# spacing modifiers
# spacing-codeblock-pre: 10pt
# spacing-codeblock-post: 10pt

#####################
## output options  ##
#####################
output:
  bookdown::pdf_book:
    template: theme/latex/template.tex
    keep_tex: true
    citation_package: biblatex  
    pandoc_args: "--lua-filter=theme/scripts/colour_and_highlight.lua"
  bookdown::bs4_book: 
    css: 
      - theme/web/bs4_style.css
      - theme/web/corrections.css # remove to stop highlighting corrections
    theme:
      primary: "#6D1919"
    # repo: https://github.com/<github-username>/<github-repo>
    pandoc_args: "--lua-filter=theme/scripts/colour_and_highlight.lua"
  bookdown::gitbook:
    css: theme/web/style.css
    config:
      sharing:
        facebook: false
        twitter: yes
        all: false
  bookdown::word_document2:
    toc: true   
link-citations: true
documentclass: book
always_allow_html: true #this allows html stuff in word (.docx) output
# The lines below make the 'knit' button render the whole thesis to PDF, HTML, or Word
# When outputting to PDF, you can clean up the files LaTeX generates by running 
# 'file.remove(list.files(pattern = "*.(log|mtc|maf|aux|bbl|blg|xml)"))' in the R console
knit: (function(input, ...) {bookdown::render_book(input, output_format = "bookdown::pdf_book")})
#knit: (function(input, ...) {bookdown::render_book(input, output_format = "bookdown::bs4_book")})
#knit: (function(input, ...) {bookdown::render_book(input, output_format = "bookdown::gitbook")})
#knit: (function(input, ...) {bookdown::render_book(input, output_format = "bookdown::word_document2")})
---


```{r install_packages, include=FALSE}
source('theme/scripts/install_packages_if_missing.R')
```

```{r create_chunk_options, include=FALSE, eval=knitr::is_latex_output()}
source('theme/scripts/create_chunk_options.R')
source('theme/scripts/wrap_lines.R')
```

<!--
Include the create_chunk_options chunk above at the top of your index.Rmd file
This will include code to create additional chunk options (e.g. for adding author references to savequotes)
and to make sure lines in code soft wrap
If you need to create your own additional chunk options, edit the file scripts/create_chunk_options.R
-->

<!-- This chunk includes the front page content in HTML output -->
```{r ebook-welcome, child = 'content/00-frontmatter/_web-welcome.Rmd', eval=knitr::is_html_output()}
```
