---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2: 
    template: template/brief_template.tex
    citation_package: biblatex
documentclass: book
bibliography: content/references.bib
---
<!-- 
```{block type='savequote', include=knitr::is_latex_output(), quote_author='(ref:darwin-quote)'}
There is grandeur in this view of life, with its several powers, having been originally breathed into a few forms or into one; and that, whilst this planet has gone cycling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved.

```
(ref:darwin-quote) --- Charles Darwin [@Darwin1859]
   -->
# Customisations and extensions
<!-- \minitoc this will include a mini table of contents-->

<!-- LaTeX normally does not indent the first line after a heading - however, it does so after the mini table of contents. You can manually tell it not to with \noindent -->

\noindent This chapter describes a number of additional tips and tricks as well as possible customizations to the `oxforddown` thesis.

## Correction Highlighting

### Short, inline corrections
Highlight **short, inline corrections** by doing `[like this]{.correction}` --- the text between the square brackets will then [be highlighted in blue]{.correction} in the output.
This should work, also with [cross references (do you remember chapter \@ref(rmd-basics)?)]{.correction} or even [citations [@Shea2014]]{.correction}.

However, pandoc might get confused by citations and cross-references.
In particular, it might get confused by [this @Shea2014]{.correction}
In such cases, you could use LaTeX syntax directly. 
The correction highlighting is supplied by the [soul](https://ctan.org/pkg/soul) package, so you can do like this:

> `It doesn't get confused by \hl{this \textcite{Shea2014}}` \
> Becomes: It doesn't get confused by \hl{this \textcite{Shea2014}}.

This has the drawback of corrections then not showing up in HTML output at all, but you may only care about correction highlighting in the PDF for your examiners anyway!


### Blocks of added or changed material
Highlight entire **blocks of added or changed material** by putting them in a block of type `correction`, using the syntax ```` ```{block type='correction'} ````.^[In the **.tex** file for PDF output, this will put the content between `\begin{correction}` and `\end{correction}`; in gitbook output it will be put between `<div class="correction">` and `</div>`.]
Like so:

```{block type='correction', include=knitr::is_latex_output() | knitr::is_html_output()}
For larger chunks, like this paragraph or indeed entire figures, you can use the `correction` block type. This environment **highlights paragraph-sized and larger blocks** with the same blue colour.
```

*Note that correction blocks cannot be included in word output.*


### Stopping corrections from being highlighted
To turn off correction highlighting, go to the YAML header of **index.Rmd**, then:

- PDF output: set `corrections: false` \
- HTML output: remove or comment out `- template/corrections.css`

## Chapter bibliographies

If you would like chapter bibliographies, in addition insert the following code at the end of each chapter, and comment out the entire REFERENCES section at the end of template.tex.

```latex
\printbibliography[segment=\therefsegment,heading=subbibliography]
```

Here is a test reference for this section: @von_goethe_wilhelm_1829.

\printbibliography[segment=\therefsegment,heading=subbibliography]
